### ISSUE TITLE
Position option

### ISSUE THREAD

**Issue by TiboOpGithub** [clownless/Blockify#1]
A way (for example in mod menu) to change the position of the place where the music will be placed to top right, bottom left, bottom right and the default top left. (Also really cool mod, I like it a lot!)

**Comment by erruqietobedelete** [comment]
It may be implemented in the next updates.

**Comment by erruqietobedelete** [comment]
implemented in #5

**Comment by TiboOpGithub** [comment]
When I use the new version it crashes when I launch minecraft 
![image](https://user-images.githubusercontent.com/95926002/155215414-b6b50f06-a85f-4258-bee0-0c2294243801.png)

**Comment by erruqietobedelete** [comment]
> When I use the new version it crashes when I launch minecraft ![image](https://user-images.githubusercontent.com/95926002/155215414-b6b50f06-a85f-4258-bee0-0c2294243801.png)

Install JRE 17

**Comment by TiboOpGithub** [comment]
I should have installed it...

**Comment by erruqietobedelete** [comment]
> I should have installed it...

Change the path of Java in the launcher.

**Comment by TiboOpGithub** [comment]
How do I do that? And isn't there a way to get it to work properly because I don't think that would be helpful for other people who might have the problem?

**Comment by erruqietobedelete** [comment]
> Как я могу это сделать? И нет ли способа заставить его работать должным образом, потому что я не думаю, что это было бы полезно для других людей, у которых могут быть проблемы?

https://www.youtube.com/watch?v=6Gkju1t7rVQ

Similar as in this video, but you need to choose the path to Java 17 ([JDK](https://adoptium.net/releases.html) or JRE)
