### ISSUE TITLE
[Feature Request]: Controls 

### ISSUE THREAD

**Issue by Fowlie1** [clownless/Blockify#12]
### Describe the feature you propose

Some computers don't have number pads making it impossible to log into Spotify account, all of the keys can be re-bound but that one

**Comment by erruqietobedelete** [comment]
Authorization is bound to the Play/Pause button. You can change its binding and then log in to your account.

**Comment by Fowlie1** [comment]
No like theres no way to change the binding for opening the spotify log in

**Comment by erruqietobedelete** [comment]
Open the minecraft key bindings settings and there you can change the blockify key bindings
