### ISSUE TITLE
[Bug]: Error code 403

### ISSUE THREAD

**Issue by Rafii2198** [clownless/Blockify#13]
### Make sure you are not opening a duplicate.

- [x] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my bug.

### Minecraft version.

1.18.1

### Blockify version.

1.1.2

### Fabric API version.

0.46.6+1.18

### What happened?

Whenever I try to use controls like pause, next, previous, etc. nothing happens. When I check logs then every time I try to use any of these actions, it spills out the `403 Forbidden` code.

### Relevant log.

https://0x0.st/oqK5.txt

### Additional information.

I am using Linux, maybe this is why it is not working. I have friends on Windows who use this mod and it is working for them. We use same versions, same launcher, same mods etc. only what is different from our setup is operating system so maybe there is some problem with it (altho I am 100% sure this is the case).

**Comment by erruqietobedelete** [comment]
Do you have a Premium subscription?

**Comment by Rafii2198** [comment]
I don't, but I believe one of my friends also don't have it and it works for him. He is on vacation so I can't ask him.

**Comment by erruqietobedelete** [comment]
Maybe you have several devices connected to your spotify account? For example android tv

**Comment by Rafii2198** [comment]
I have my app on PC as well as on my phone, but I really rarely use it.

**Comment by Rafii2198** [comment]
Alright, it just so happens that my mom bought me Premium as a gift for passing important exam and now it works. So that means that Premium is needed for controlling the songs. I think it would be good information to put into description so other people wouldn't be confused as me.
