### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rhbarber** [clownless/Blockify#17]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my bug.

### Spotify premium subscription.

- [X] I have a Spotify Premium subscription.

### Minecraft version.

1.18.2

### Blockify version.

1.1.3

### Fabric API version.

qsl-1.1.0-beta.6_qfapi-1.0.0-beta.10_fapi-0.51.1_mc-1.18.2

### What happened?

When mod updates to show the next song information, FPS drops to zero.

### Relevant log.

https://paste.sparked.host/ujaxolabiz.yaml

### Additional information.

Mods list: https://rhbarber.com/ss/itl15.png

**Comment by erruqietobedelete** [comment]
This happens during the rendering of the album image. Unfortunately, I do not know how to improve this process. Perhaps I will make a setting thanks to which it will be possible to disable the rendering of the album image.

**Comment by erruqietobedelete** [comment]
> This happens during the rendering of the album image. Unfortunately, I do not know how to improve this process. Perhaps I will make a setting thanks to which it will be possible to disable the rendering of the album image.

Implemented https://github.com/clownless/Blockify/commit/605a71b77f1d0f1a2d155a0308b64010f07a8495
