### ISSUE TITLE
Buttons don't work

### ISSUE THREAD

**Issue by TiboOpGithub** [clownless/Blockify#2]
The buttons to go to the next song or stop the song don't work for me. (below a clip, believe me I pressed the buttons xD)

https://user-images.githubusercontent.com/95926002/153746939-3f156a4e-62ff-440f-a3e3-47930e93cf5c.mp4

**Comment by erruqietobedelete** [comment]
> The buttons to go to the next song or stop the song don't work for me. (below a clip, believe me I pressed the buttons xD)
> 
>  Bug.blockify_Trim.mp4

pls give logs (%Appdata%\.minecraft\logs\latest.log)

**Comment by TiboOpGithub** [comment]
[latest.log](https://github.com/clownless/Blockify/files/8056027/latest.log)
Here is the log

**Comment by erruqietobedelete** [comment]
> [latest.log](https://github.com/clownless/Blockify/files/8056027/latest.log)
> Here is the log

Try joining the server with a Spotify's shut off and after that, try switching tracks

**Comment by clownless** [comment]
> [latest.log](https://github.com/clownless/Blockify/files/8056027/latest.log)
> Here is the log

Try joining the server with a Spotify's shut off and after that, try switching tracks

**Comment by TiboOpGithub** [comment]
> > [latest.log](https://github.com/clownless/Blockify/files/8056027/latest.log)
> > Here is the log
> 
> Try joining the server with a Spotify's shut off and after that, try switching tracks

Also does not work

**Comment by erruqietobedelete** [comment]
> The buttons to go to the next song or stop the song don't work for me. (below a clip, believe me I pressed the buttons xD)
> 
>  Bug.blockify_Trim.mp4

Spotify web?

**Comment by TiboOpGithub** [comment]
> > The buttons to go to the next song or stop the song don't work for me. (below a clip, believe me I pressed the buttons xD)
> > Bug.blockify_Trim.mp4
> 
> Spotify web?

no

**Comment by erruqietobedelete** [comment]
Spotify API Issue

**Comment by TiboOpGithub** [comment]
That is very unfortunate... Is there a way to make sure it works anyway?

**Comment by TiboOpGithub** [comment]
I haven't used the mod in a while but since I used it again today it worked! Maybe because I recently got spotify premium, no idea but the most important thing is that it works.
