### ISSUE TITLE
Long text

### ISSUE THREAD

**Issue by TiboOpGithub** [clownless/Blockify#3]
When the text from te song is to long it goes off-plane. Maybe it's useful that the first word that can't be added goes to the next row..
![2022-02-13_17 24 50](https://user-images.githubusercontent.com/95926002/153762648-1f535d4a-b513-4733-8afd-73a50a66c651.png)

**Comment by erruqietobedelete** [comment]
> When the text from te song is to long it goes off-plane. Maybe it's useful that the first word that can't be added goes to the next row..
> ![2022-02-13_17 24 50](https://user-images.githubusercontent.com/95926002/153762648-1f535d4a-b513-4733-8afd-73a50a66c651.png)
> 

I will take it

**Comment by clownless** [comment]
> When the text from te song is to long it goes off-plane. Maybe it's useful that the first word that can't be added goes to the next row..
> ![2022-02-13_17 24 50](https://user-images.githubusercontent.com/95926002/153762648-1f535d4a-b513-4733-8afd-73a50a66c651.png)
> 

I will take it
