### ISSUE TITLE
[Bug]: Breaks with Spotify DJ

### ISSUE THREAD

**Issue by srnyx** [clownless/Blockify#30]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my bug.

### Spotify premium subscription.

- [X] I have a Spotify Premium subscription.

### Minecraft version.

1.19.2

### Blockify version.

1.2.4.1

### Fabric API version.

0.76.0+1.19.2

### What happened?

When a song ends and DJ starts speaking it still says the song is playing. When DJ stops talking and starts playing the next song, it doesn't update and still shows the previous song is playing.

### Relevant log.

N/A

### Additional information.

- https://support.spotify.com/us/article/dj
- https://newsroom.spotify.com/2023-02-22/spotify-debuts-a-new-ai-dj-right-in-your-pocket

**Comment by erruqietobedelete** [comment]
irrelevant
