### ISSUE TITLE
[Bug]: Blockify wont detect spotify premium

### ISSUE THREAD

**Issue by pawfix** [clownless/Blockify#31]
### Make sure you are not opening a duplicate.

- [X] [I have searched the issue tracker](https://github.com/clownless/Blockify/issues?q=) and did not find an issue describing my bug.

### Spotify premium subscription.

- [X] I have a Spotify Premium subscription.

### Minecraft version.

1.21.3

### Blockify version.

1.2.6-unstavle

### Fabric API version.

0.109.0+1.21.3

### What happened?

Pressing home Gives me: Spotify premium is reqired  for this feature
![Premium](https://github.com/user-attachments/assets/30cc1dd7-e492-4d21-a5e3-5d012f2f90e4)
![2024-11-24_12 23 56](https://github.com/user-attachments/assets/d2ee88f7-3f45-4709-9b22-93411b559b6c)

### Relevant log.

https://hastebin.com/share/emedelacan.markdown

**Comment by erruqietobedelete** [comment]
try delete `blockifyTokens.json` from `.minecraft/config`, download mod from latest release and reinstall
