### ISSUE TITLE
Songtext box idea

### ISSUE THREAD

**Issue by TiboOpGithub** [clownless/Blockify#7]
Hi! 
The version 1.1 of the mod unfortunately doesn't work for me at the moment as you know but I do have an idea! Is it possible to make a function that at the top of your minecraft screen there will be a box with part of the lyrics of the song (1 line seems sufficient to me). And maybe also the possibility to adjust this like what happened in the Blockify 1.1 update.

This is what I meant:
![image](https://user-images.githubusercontent.com/95926002/155884307-a0fcd91c-f3de-4df0-899f-c4a82a342356.png)
![image](https://user-images.githubusercontent.com/95926002/155884319-542c1abf-487b-4570-9b53-60f384a3cc41.png)

**Comment by erruqietobedelete** [comment]
bad idea imho

**Comment by TiboOpGithub** [comment]
Nah, maybe it won't come in handy for you, but I do think that some people find it useful/fun and it can be a cool enhancement for the future.
