### ISSUE TITLE
[bug] crash on song change and advert plays

### ISSUE THREAD

**Issue by MissGamerz** [clownless/Blockify#9]
minecraft: 1.18.2
Fabric loader: 0.13.3
Fabric API: 0.47.10

modlist in log

Log:
[crash-2022-03-13_16.48.44-client.txt](https://github.com/clownless/Blockify/files/8240183/crash-2022-03-13_16.48.44-client.txt)

**Comment by erruqietobedelete** [comment]
i have no way to fix this at the moment, because I don't have an account without a subscription
